--Load Task

CREATE OR REPLACE TASK SHPROD.PUBLIC.LOAD_PASSPORT_JOB
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 58 23 * * * Asia/Kolkata'
AS
EXECUTE IMMEDIATE $$
BEGIN
    TRUNCATE TABLE SHPROD.PUBLIC.RANK_PASSPORT_RD;
    
    COPY INTO SHPROD.PUBLIC.RANK_PASSPORT_RD (rid, cntry, rnk, access_no_country, yr)
    FROM (
        SELECT 
            ROW_NUMBER() OVER (ORDER BY s.$1), -- Generates 1, 2, 3... based on country name
            s.$1, s.$2, s.$3, s.$4 
        FROM @SHPROD.PUBLIC.LOADDATA/henleypassportindex.csv (FILE_FORMAT => SHPROD.PUBLIC.CSV_FORMAT) s
    )
    FORCE = TRUE;

END;
$$;


--Runlog Task

CREATE OR REPLACE TASK SHPROD.PUBLIC.START_RUNLOG_JOB
    --WAREHOUSE = 'COMPUTE_WH'
    --SCHEDULE = 'USING CRON 10 17 * * * Asia/Kolkata'
    AFTER SHPROD.PUBLIC.LOAD_PASSPORT_JOB
AS
EXECUTE IMMEDIATE $$
BEGIN
        -- 1️⃣ Insert the log entry
INSERT INTO SHPROD.PUBLIC.RUNLOG (start_ts, status)
VALUES (CURRENT_TIMESTAMP, 'STARTED');

-- 2️⃣ Update the yrs column
UPDATE SHPROD.PUBLIC.RUNLOG L
SET L.YRS = R.YR
FROM SHPROD.PUBLIC.RANK_PASSPORT_RD R
WHERE L.STATUS = 'STARTED' 
  AND L.END_TS IS NULL      -- 🚩 Fixed: Use IS NULL instead of = NULL
  AND (L.YRS < R.YR OR L.YRS IS NULL); -- Handles cases where L.YRS starts as NULL


END;
$$;





--Pre Validate Task

CREATE OR REPLACE TASK  SHPROD.PUBLIC.VALIDATE_PASSPORT_JOB
AFTER SHPROD.PUBLIC.START_RUNLOG_JOB
AS
CALL SHPROD.PUBLIC.sp_validate_passport();






-- SCD Task

CREATE OR REPLACE TASK  SHPROD.PUBLIC.SCD_PASSPORT_JOB
AFTER SHPROD.PUBLIC.VALIDATE_PASSPORT_JOB
AS
CALL SHPROD.PUBLIC.sp_passport_scd();


--Close Runlog Task

CREATE OR REPLACE TASK SHPROD.PUBLIC.CLOSE_RUNLOG_JOB    
AFTER SHPROD.PUBLIC.SCD_PASSPORT_JOB
AS
EXECUTE IMMEDIATE $$
BEGIN

       
-- 1️⃣ MARK THE FINAL STATUS
UPDATE SHPROD.PUBLIC.RUNLOG L
SET L.STATUS = E.STATUS,
L.end_ts = CURRENT_TIMESTAMP()
FROM SHPROD.PUBLIC.EXECUTION_LOGS E
WHERE L.STATUS = 'STARTED' 
  AND L.RUN_ID = E.RUN_ID;

END;
$$;




-- Don't forget to resume!
ALTER TASK SHPROD.PUBLIC.LOAD_PASSPORT_JOB RESUME;
SHOW TASKS;
