--Load Task

CREATE OR REPLACE TASK LOAD_PASSPORT_JOB
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 58 23 * * * Asia/Kolkata'
AS
EXECUTE IMMEDIATE $$
BEGIN
    TRUNCATE TABLE RANK_PASSPORT_RD;
    
    COPY INTO RANK_PASSPORT_RD (rid, cntry, rnk, access_no_country, yr)
    FROM (
        SELECT 
            ROW_NUMBER() OVER (ORDER BY s.$1), -- Generates 1, 2, 3... based on country name
            s.$1, s.$2, s.$3, s.$4 
        FROM @LOADDATA/henleypassportindex.csv (FILE_FORMAT => SHPROD.PUBLIC.CSV_FORMAT) s
    )
    FORCE = TRUE;

END;
$$;


--Runlog Task

CREATE OR REPLACE TASK START_RUNLOG_JOB
    --WAREHOUSE = 'COMPUTE_WH'
    --SCHEDULE = 'USING CRON 10 17 * * * Asia/Kolkata'
    AFTER LOAD_PASSPORT_JOB
AS
EXECUTE IMMEDIATE $$
BEGIN
        -- 1️⃣ Insert the log entry
INSERT INTO RUNLOG (start_ts, status)
VALUES (CURRENT_TIMESTAMP, 'STARTED');

-- 2️⃣ Update the yrs column
UPDATE RUNLOG L
SET L.YRS = R.YR
FROM RANK_PASSPORT_RD R
WHERE L.STATUS = 'STARTED' 
  AND L.END_TS IS NULL      -- 🚩 Fixed: Use IS NULL instead of = NULL
  AND (L.YRS < R.YR OR L.YRS IS NULL); -- Handles cases where L.YRS starts as NULL


END;
$$;





--Pre Validate Task

CREATE OR REPLACE TASK  VALIDATE_PASSPORT_JOB
AFTER START_RUNLOG_JOB
AS
CALL sp_validate_passport();






-- SCD Task

CREATE OR REPLACE TASK  SCD_PASSPORT_JOB
AFTER VALIDATE_PASSPORT_JOB
AS
CALL sp_passport_scd();


--Close Runlog Task

CREATE OR REPLACE TASK CLOSE_RUNLOG_JOB    
AFTER SCD_PASSPORT_JOB
AS
EXECUTE IMMEDIATE $$
BEGIN

       
-- 1️⃣ MARK THE FINAL STATUS
UPDATE RUNLOG L
SET L.STATUS = E.STATUS,
L.end_ts = CURRENT_TIMESTAMP()
FROM EXECUTION_LOGS E
WHERE L.STATUS = 'STARTED' 
  AND L.RUN_ID = E.RUN_ID;

END;
$$;




-- Don't forget to resume!


ALTER TASK CLOSE_RUNLOG_JOB RESUME;
ALTER TASK SCD_PASSPORT_JOB RESUME;
ALTER TASK VALIDATE_PASSPORT_JOB RESUME;
ALTER TASK START_RUNLOG_JOB RESUME;
ALTER TASK LOAD_PASSPORT_JOB RESUME;

SHOW TASKS;
